version: '3.8'

services:
  backend:
    build: ./server
    container_name: chat-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017/chatdb
    depends_on:
      - mongo

  frontend:
    build: ./public
    container_name: chat-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_LOCALHOST_KEY="chat-app-current-user"
      - WDS_SOCKET_PORT=0
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: